version: '3'
services:
  service-a:
    build:
      context: .
      dockerfile: service-a/Dockerfile
    ports:
      - "8081:8081"
  service-b:
    build:
      context: .
      dockerfile: service-b/Dockerfile
    ports:
      - "8082:8082"
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "16686:16686"     # Jaeger UI  
      - "6831:6831/udp"   # Thrift Udp Compact    
    command: ["--reporter.grpc.host-port=otel-collector:14250"] 
    #command: ["--reporter.grpc.host-port=jaeger-logzio:14250"] # Alternative way /uses logzio-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.17.0
    container_name: otel-logzio
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./config.yaml:/etc/otel-collector-config.yml
    ports:      
      - "13133:13133" # health_check extension
    depends_on:
      - jaeger
  
  # Alternative way of streaming tarces to logzio
  # jaeger-logzio: 
  #   image: logzio/jaeger-logzio-collector:latest
  #   container_name: jaeger-logzio
  #   ports:
  #     - 14268:14268
  #     - 14269:14269
  #     - 14250:14250
  #   environment:
  #     ACCOUNT_TOKEN: #<YOUR_TOKEN_GOES_HERE>
  #     REGION: #<YOUR_REGION_CODE_GOES_HERE>
  #     GRPC_STORAGE_PLUGIN_LOG_LEVEL: 
  