version: "3.9"

services:
  service-a:
    build: service-a
    ports:
      - "8081:8081"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
  service-b:
    build: service-b
    ports:
      - "8082:8082"
    networks:
      app_net:
        ipv4_address: 172.16.238.11
  jaeger:
    image: jaegertracing/all-in-one:1.24
    container_name: jaegertracing
    ports:
      - "16686:16686"     # Jaeger UI  
      - "6831:6831/udp"   # Thrift Udp Compact
    networks:
      app_net:
        ipv4_address: 172.16.238.12

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"
